# Generated by Django 4.1.1 on 2022-09-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagetable",
            name="file",
            field=models.ImageField(upload_to=""),
        ),
    ]
