# Generated by Django 4.1.1 on 2022-09-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_alter_imagetable_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagetable",
            name="filename",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
