# Generated by Django 4.1.1 on 2022-10-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0005_testtable_answers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testreport",
            name="email",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="testreport",
            name="user_name",
            field=models.CharField(max_length=100),
        ),
    ]
