# Generated by Django 3.2 on 2022-10-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_alter_testreport_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_token', models.CharField(max_length=200, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
