# Generated by Django 3.2 on 2022-10-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_testtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtoken',
            name='used',
        ),
        migrations.AddField(
            model_name='testtoken',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
