# Generated by Django 3.2 on 2022-10-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_auto_20221004_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtoken',
            name='email',
            field=models.CharField(default='iskender.berdiev@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testtoken',
            name='send_results',
            field=models.BooleanField(default=False),
        ),
    ]
