# Generated by Django 3.2 on 2022-10-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_testtoken_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testreport',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testreport',
            name='time_taken',
            field=models.CharField(default='1 minute', max_length=100),
            preserve_default=False,
        ),
    ]
