# Generated by Django 3.2 on 2022-10-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_auto_20221005_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='prompt',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
